config {
    type: "incremental", 
    schema: "gold",
    name: "dim_sku_organisation",
    tags: "sku_order_pipeline",
    disabled: true,
    description: "Contains all Organization information",
    uniqueKey: ["orgId"]
}

SELECT DISTINCT  
  json_value(data, '$.payload.organization.id') orgId, 
  json_value(data, '$.payload.organization.name') orgName, 
  cast(json_value(data, '$.payload.organization.isFbs') as BOOL) isFbs, 
  json_value(data, '$.payload.organization.ownerUserId') ownerUserId, 
  sys_extract_ts sys_extract_ts
  ${utils.auditColumns()}
FROM 
     ${ref("silver", "sku_sales_order")}  
WHERE type='ORGANIZATION_REGISTERED'
${ when(incremental(), `AND DATE(sys_extract_ts) >= DATE_SUB(current_date, INTERVAL 1 DAY)`) }
